# automatic testing with Travis CI!

language:
  - node_js

node_js:
  - "11"

addons:
  chrome: stable

cache:
  npm: true
  directories:
    - node_modules

before_script:
  - npm install

script:
  - npm run test

notifications:
  email:
    # If you don't want to specify emails here,
    # you can set your email with git config --global user.email
    on_success: change
    on_failure: always
